### ISSUE TITLE
Numpy 2.0 Support

### ISSUE THREAD

**Issue by Tobias314** [j3soon/tbparse#19]
It would be cool if tbparse works with Numpy 2.0.

Currently, this does not seem to be the case. However, it should be quite easy to change this. It might already be enough to use `np.nan` instead of `np.NaN` [here](https://github.com/j3soon/tbparse/blob/a58179dadaa83a0a567be43c46387c0ea216911b/tbparse/summary_reader.py#L852).

Some more tests and minor fixes might be required though to ensure full compatibility. 

In any case support for Numpy 2.0 would be highly appreciated as Numpy 2.0 will likely become the default in the future and will also be required by more and more third-party packages.

**Comment by j3soon** [comment]
Thanks for the information! You're right that the simple change will do the trick.

I've pushed a fix, and the latest commit (currently require [`tb-nightly`](https://pypi.org/project/tb-nightly)) should now support Numpy 2.0.

We'll need to wait for the tensorboard 2.17.1 patch release ([source](https://github.com/tensorflow/tensorboard/issues/6869#issuecomment-2286861336)) before we can remove the `tb-nightly` dependency.

**Comment by j3soon** [comment]
Fixed in v0.0.9 on PyPI.
