### ISSUE TITLE
cannot install via pip

### ISSUE THREAD

**Issue by NtaylorOX** [j3soon/tbparse#7]
I am trying to install tbparse and getting nowhere.

```
(nlp_projects) niallt@doraemon1:~$ pip install tbparse
ERROR: Could not find a version that satisfies the requirement tbparse (from versions: none)
ERROR: No matching distribution found for tbparse

```

I have tried using a fresh virtual environment to no success. Any thoughts?

**Comment by j3soon** [comment]
Are you using Python 3.6 or older versions?

tbparse only supports Python version >= 3.7

**Comment by NtaylorOX** [comment]
Damn! That is my bad - I had presumed I was using python 3.7 but in fact, it was 3.6.9. 

I am very sorry!!

**Comment by j3soon** [comment]
No problem!
